// Code generated by "stringer -type=CookType -trimprefix=Cook"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CookFull-0]
	_ = x[CookIncremental-1]
	_ = x[CookIterative-2]
}

const _CookType_name = "FullIncrementalIterative"

var _CookType_index = [...]uint8{0, 4, 15, 24}

func (i CookType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CookType_index)-1 {
		return "CookType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CookType_name[_CookType_index[idx]:_CookType_index[idx+1]]
}
